include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
